services:
  embeddings:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/embeddings
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/embeddings:/app
      - ~/.cache:/home/${USERNAME}/.cache:cached
    ports:
      - "8803:8803"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  sam3:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/sam3
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/sam3:/app
      - ~/.cache:/home/${USERNAME}/.cache:cached
    ports:
      - "8805:8805"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  pipeline:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/pipeline
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    restart: unless-stopped
    ports:
      - "8800:8800"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/pipeline:/app
      - /data/plant-rl:/data
      - ~/.cache:/home/${USERNAME}/.cache:cached
    depends_on:
      - embeddings
      - sam3

networks:
  plant-network:
    name: plant-network
