services:
  embeddings:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/embeddings
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/embeddings:/app
      - ~/.cache:/home/${USERNAME}/.cache:cached
    ports:
      - "8803:8803"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  grounding-dino:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/grounding_dino
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/grounding_dino:/app
      - ~/.cache:/home/${USERNAME}/.cache:cached
    ports:
      - "8801:8801"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  segment-anything:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/segment_anything
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/segment_anything:/app
      - ~/.cache:/home/${USERNAME}/.cache:cached
    ports:
      - "8802:8802"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  pipeline:
    build:
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
      context: api/pipeline
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    restart: unless-stopped
    ports:
      - "8800:8800"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./api/pipeline:/app
      - /data/plant-rl:/data
      - ~/.cache:/home/${USERNAME}/.cache:cached
    depends_on:
      - embeddings
      - grounding-dino
      - segment-anything

networks:
  plant-network:
    name: plant-network
