services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - plant-network
    volumes:
      - ..:/workspaces:cached
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.config:/root/.config:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/.netrc:/root/.netrc:cached
      - /data/plant-rl:/data:cached
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  embeddings:
    build:
      context: api/embeddings
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./api/embeddings:/app
      - ~/.cache:/home/docker/.cache:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  grounding-dino:
    build:
      context: api/grounding_dino
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./api/grounding_dino:/app
      - ~/.cache:/home/docker/.cache:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  segment-anything:
    build:
      context: api/segment_anything
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - plant-network
    privileged: true
    restart: unless-stopped
    volumes:
      - ./api/segment_anything:/app
      - ~/.cache:/home/docker/.cache:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  pipeline:
    build:
      context: api/pipeline
      dockerfile: Dockerfile
    networks:
      - plant-network
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./api/pipeline:/app
    depends_on:
      - embeddings
      - grounding-dino
      - segment-anything

networks:
  plant-network:
    name: plant-network
