[project]
name = "grounding-dino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litserve>=0.2.8",
    "pillow>=11.2.1",
    "pip>=25.3",
    "torch>=2.7.0",
    "transformers>=4.51.2",
]
